name: Run

# Build runs on master merges and pull request changes
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CI: true
  FORCE_COLOR: true
  BP_DATE: not accepting

jobs:

  build:
    name: 'Run'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Install Node.js'
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12.x
      - name: 'Install Dependencies'
        run: |
          npm ci
      - name: 'Run'
        run: |
          CYPRESS_BP_USERNAME="${{ secrets.BP_USERNAME }}" CYPRESS_BP_PASSWORD="${{ secrets.BP_PASSWORD }}" CYPRESS_BP_DATE="${{ env.BP_DATE }}" npm run check
