name: Run

# Build runs on schedule, on master merges and pull request changes
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '*/5 * * * *'

env:
  CI: true
  FORCE_COLOR: true

jobs:

  build:
    name: 'Run'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        location: ['Framingham']
        date: ['Feb 22', 'Feb 23', 'Feb 24']
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Install Node.js'
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12.x
      - name: 'Install Dependencies'
        run: |
          npm ci
      - name: 'Run'
        run: |
          # Run Cypress, but suppress exit code
          CYPRESS_BP_USERNAME="${{ secrets.BP_USERNAME }}" CYPRESS_BP_PASSWORD="${{ secrets.BP_PASSWORD }}" CYPRESS_BP_LOCATION="${{ matrix.location }}" CYPRESS_BP_DATE="${{ matrix.date }}" npm run monitoring
          exit 0
        shell: bash {0}
      - name: 'Check Monitoring Status'
        id: 'check_status'
        uses: andstor/file-existence-action@v1
        with:
          files: 'success.txt'
      - name: 'Notify Slack'
        uses: lazy-actions/slatify@v3.0.0
        if: (steps.check_status.outputs.files_exists == 'true')
        with:
          url: ${{ secrets.SLACK_WEBHOOK }}
          type: ${{ job.status }}
          job_name: 'Found Project Beacon appointment in ${{ matrix.location }} for ${{ matrix.date }} -'
