name: Run

# Build runs on schedule, on master merges and pull request changes
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '*/5 * * * *'

env:
  CI: true
  FORCE_COLOR: true
  BP_DATE: Dec 28

jobs:

  build:
    name: 'Run'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Install Node.js'
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12.x
      - name: 'Install Dependencies'
        run: |
          npm ci
      - name: 'Run'
        run: |
          CYPRESS_BP_USERNAME="${{ secrets.BP_USERNAME }}" CYPRESS_BP_PASSWORD="${{ secrets.BP_PASSWORD }}" CYPRESS_BP_DATE="${{ env.BP_DATE }}" npm run check
#      - name: 'Store Cypress Videos'
#        uses: actions/upload-artifact@v2
#        if: failure()
#        with:
#          name: cypress-videos
#          path: cypress/videos/
      - name: 'Notify Slack'
        uses: lazy-actions/slatify@v3.0.0
        if: success()
        with:
          url: ${{ secrets.SLACK_WEBHOOK }}
          type: ${{ job.status }}
          job_name: 'Found Project Beacon appointment for ${{ env.BP_DATE }} -'
